check the branch/ref exists before trying to use it (resolved #2)

diff --git a/detoul-base b/detoul-base
--- a/detoul-base
+++ b/detoul-base
@@ -30,12 +30,20 @@ make-detoul-dependency() {
 }
 
 autocomplete() {
-  branch_name="$(git branch -a | sed -e 's/remotes\/[[:alnum:]]\+\///g' | cut -c3- | grep "^$1" | head -n 1)"
+  branch_name="$((git branch -a | cut -c3- ; git tag) | sed -e 's/remotes\/[[:alnum:]]\+\///g' | grep "^$1" | head -n 1)"
   if [ "$branch_name" == "" ]; then
     echo "$1"
   else
     echo "$branch_name"
   fi
+}
+
+validate-branch-name() {
+  (git branch -a | cut -c3- ; git tag) | sed -e 's/remotes\/[[:alnum:]]\+\///g' | grep -q "^$1$"
+}
+
+validate-ref-name() {
+  validate-branch-name "$1" || git show "$1" >/dev/null 2>&1
 }
 
 checkout() {
@@ -166,6 +174,10 @@ while read -r line; do
   command=($line)
   branch="$(autocomplete "${command[1]//\*/.*}")"
   (make-detoul-dependency "$branch") || fail
+  if ! validate-ref-name "$branch" ; then
+    echo -e "\e[31mReference not found: '$branch'.\e[0m" >&2
+    fail
+  fi
   case "${command[0]}" in
     checkout)
       checkout
